version: '3.8'

services:
  gateway:
    image: devopsfaith/krakend:latest
    volumes:
      - ./krakend/krakend.json:/etc/krakend/krakend.json:ro
    ports:
      - "8080:8080"
      - "8090:8090"
    depends_on:
      - api
    environment:
      - FC_ENABLE=0
    networks:
      - app-network

  api:
    build: .
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=urlshortener
      - DB_USER=postgres
      - DB_PASS=postgres
      - JWT_SECRET=123
      - JWT_EXPIRATION=24h
      - BASE_URL=http://localhost:8080/r
      - ENABLE_METRICS=true
      - ENABLE_TELEMETRY=true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=urlshortener
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge