apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: url-shortener

resources:
- ../../base

patches:
- path: hpa.yaml

configMapGenerator:
- name: app-config
  behavior: merge
  literals:
  - NODE_ENV=production
  - LOG_LEVEL=info 