apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  PORT: "3000"
  NODE_ENV: "development"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "url_shortener"
  DB_USER: "postgres"
  BASE_URL: "http://localhost:3000"