apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
  namespace: url-shortener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: krakend
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
      - name: krakend
        image: devopsfaith/krakend:latest
        ports:
        - containerPort: 8080
        - containerPort: 8090
        volumeMounts:
        - name: krakend-config
          mountPath: /etc/krakend
        env:
        - name: FC_ENABLE
          value: "0"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: krakend-config
        configMap:
          name: krakend-config
---
apiVersion: v1
kind: Service
metadata:
  name: krakend
  namespace: url-shortener
spec:
  type: LoadBalancer
  selector:
    app: krakend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: metrics
    port: 8090
    targetPort: 8090 