apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- api-service.yaml
- krakend-service.yaml
- postgres.yaml
- configmap.yaml
- secret.yaml

commonLabels:
  app.kubernetes.io/name: url-shortener
  app.kubernetes.io/instance: url-shortener

namespace: url-shortener 